version: '3.8'

services:

  mysql:
    image: mysql:9.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: library_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WAR_FILE: user-service-user.war
    container_name: user-service
    ports:
      - "8081:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: library_db
      DB_USER: admin
      DB_PASSWORD: password
    depends_on:
      - mysql

  admin-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WAR_FILE: admin-service-admin.war
    container_name: admin-service
    ports:
      - "8082:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: library_db
      DB_USER: admin
      DB_PASSWORD: password
    depends_on:
      - mysql

volumes:
  mysql-data:

