apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8080       # Port exposed inside the cluster
      targetPort: 8080 # Port your container listens on
  type: NodePort       # Change to ClusterIP or LoadBalancer as needed
